### ISSUE TITLE
open Multiple files pcap file for offline analysis at the same time

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#156] opened 2017-10-06 06:45 UTC
- I have multiple files.Each file 2G size.

1. aaa01.pcap
2. aaa02.pcap
3. aaa03.pcap

- I hope:
sensor.py -i aaa*.pcap

**Comment by rickhg12hs** [comment] 2020-11-26 09:48
Same as #1587?

**Comment by stamparm** [comment] 2020-11-26 22:07
@rickhg12hs yup. thx. closing as duplicate

**Comment by stamparm** [comment] 2020-11-26 22:07
Duplicate of #1587 (solved)

**Closed by stamparm** 2020-11-26 22:07 UTC
Labels: duplicate
