### ISSUE TITLE
api:how to curl maltrail info

### ISSUE THREAD

**Issue by andyoulovexy** [stamparm/maltrail#19222] opened 2023-11-13 07:55 UTC
I want to curl severity and so on?how to get it in commandline?
![图片](https://github.com/stamparm/maltrail/assets/38940994/3dd1e23e-cb16-4a24-a9d9-0be7ccf4d364)

**Comment by MikhailKasimov** [comment] 2023-11-13 08:20
Hello! You want to pass maltrail info to some external log-collector, right?

**Comment by andyoulovexy** [comment] 2023-11-13 08:33
> Hello! You want to pass maltrail info to some external log-collector, right?

I just want to get severity ,src_ip,src_port info and so on by comandline

**Comment by MikhailKasimov** [comment] 2023-11-13 14:44
Something like ```curl -X POST <link> -H "severity" -H "src_ip" ... - H "what is needed"```

**Comment by andyoulovexy** [comment] 2023-11-13 17:03
> Something like `curl -X POST <link> -H "severity" -H "src_ip" ... - H "what is needed"`
Yes

**Comment by stamparm** [comment] 2023-11-15 12:52
duplicate of #19223

**Closed by stamparm** 2023-11-15 12:52 UTC
